#!/bin/bash
DIR="`dirname "$0"`"
OLIB=LD_LIBRARY_PATH="$LD_LIBRARY_PATH"

export LD_LIBRARY_PATH="$OLIB:pref;bin_linux/"
find "$DIR"/data/ -maxdepth 1 -print0  | sed 's/^/-k/' -z | xargs --null bin_linux/inexor -q"~/.inexor" && exit
