#!/bin/bash

dir="`dirname "$0"`"
exe="${dir}/bin/inexor"

# Maybe we need to set them to the conan lib dirs:
export LD_LIBRARY_PATH="$bin:$LD_LIBRARY_PATH"

source inexor_node_unix&
echo >&2 "CALLING: ${exe}"
find "$dir"/media/ -maxdepth 1 -print0                      \
  | sed 's/^/-k/' -z                                       \
  | xargs --null "${exe}" -q"~/.inexor"

# Kill all remaining jobs in the very end
kill $!
